apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-app  
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2  
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{DOCKER_IMAGE_BACKEND}}  
        ports:
        - containerPort: 5000  
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017/mern-app  # Change database name if needed
        - name: NODE_ENV
          value: production
        # Add any additional environment variables your app needs
