apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mern-app  # Match your namespace from namespace.yaml
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1  # Adjust replicas based on your needs
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo  # Specify version if needed: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: mern-app  # Match your namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size based on your needs
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mern-app  # Match your namespace
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017